package a15;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AddStudent extends javax.swing.JFrame {

	ArrayList<Student> students;

	/**
	 * Creates new form AddStudent
	 */
	public AddStudent() {
		initComponents();
		students = new ArrayList<Student>();
		populateArrayList();
		saveStudentsToFile(false);
	}

	public void populateArrayList() {
		try {
			FileInputStream file = new FileInputStream("Students.dat");
			ObjectInputStream inputFile = new ObjectInputStream(file);
			boolean test = false;
			while (!test) {
				try {
					students.add((Student) inputFile.readObject());
				} catch (EOFException e) {
					test = true;
				}
			}
			inputFile.close();
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "error has ocurred " + e.getMessage());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "error has ocurred " + e.getMessage());
		}
	}

	// The boolean tells me whether I am running this from the constructor (in which case I don't want to show SAVED) or after pressing the button (in which case I do)
	public void saveStudentsToFile(boolean showSaved) {
		try {
			FileOutputStream file = new FileOutputStream("Students.dat");
			ObjectOutputStream outputFile = new ObjectOutputStream(file);
			for (int i = 0; i < students.size(); i++) {
				outputFile.writeObject(students.get(i));
			}
			outputFile.close();
			if (showSaved) {
				JOptionPane.showMessageDialog(null, "SAVED");
			}
			this.dispose();
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "error has ocurred" + e.getMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jFirstName = new javax.swing.JTextField();
		jLastName = new javax.swing.JTextField();
		jAge = new javax.swing.JTextField();
		jGender = new javax.swing.JTextField();
		jStudentNumber = new javax.swing.JTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Frist Name");

		jLabel2.setText("Last Name");

		jLabel3.setText("Age");

		jLabel4.setText("Gender");

		jLabel5.setText("Student Number");

		jButton1.setText("Save");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jMenu1.setText("Add Student");
		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(26, 26, 26)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jStudentNumber, javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(0, 0, Short.MAX_VALUE)
																.addComponent(jButton1)))
												.addGap(26, 26, 26))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel5)
																.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
														.addComponent(jAge, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
														.addComponent(jFirstName))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(jGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
																		.addComponent(jLastName, javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(26, 26, 26))))))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
								.addComponent(jButton1)
								.addContainerGap())
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		if (jFirstName.getText().isEmpty() || jLastName.getText().isEmpty() || jAge.getText().isEmpty() || jGender.getText().isEmpty() || jStudentNumber.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "INVALID INPUT");
		} else {
			String firstName = jFirstName.getText();
			String lastName = jLastName.getText();
			// TODO need a try catch for integer 
			int age = Integer.parseInt(jAge.getText());
			String gender = jGender.getText();
			String studentNumber = jStudentNumber.getText();
			ArrayList<LibraryBook> placeholderBooks = new ArrayList<LibraryBook>();

			// named it studentVar to avoid confusion
			Student studentVar = new Student(studentNumber, placeholderBooks, firstName, lastName, age, gender);
			students.add(studentVar);
			saveStudentsToFile(true);
		}
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddStudent().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JTextField jFirstName;
	private javax.swing.JTextField jLastName;
	private javax.swing.JTextField jAge;
	private javax.swing.JTextField jGender;
	private javax.swing.JTextField jStudentNumber;
	// End of variables declaration//GEN-END:variables
}
