package a15;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class EditBook extends javax.swing.JFrame {

	ArrayList<LibraryBook> books;

	public EditBook() {
		initComponents();
		books = new ArrayList<LibraryBook>();
		populateArrayList();

		String booksArray[] = new String[books.size()];
		for (int i = 0; i < books.size(); i++) {
			booksArray[i] = books.get(i).getISBN();
		}
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(booksArray));
	}

	public void populateArrayList() {
		try {
			FileInputStream file = new FileInputStream("Books.dat");
			ObjectInputStream inputFile = new ObjectInputStream(file);
			boolean test = false;
			while (!test) {
				try {
					books.add((LibraryBook) inputFile.readObject());
				} catch (EOFException e) {
					test = true;
				}
			}
			inputFile.close();
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "error has ocurred " + e.getMessage());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "error has ocurred " + e.getMessage());
		}
	}

	public void saveBooksToFile() {
		try {
			FileOutputStream file = new FileOutputStream("Books.dat");
			ObjectOutputStream outputFile = new ObjectOutputStream(file);
			for (int i = 0; i < books.size(); i++) {
				outputFile.writeObject(books.get(i));
			}
			outputFile.close();
			JOptionPane.showMessageDialog(null, "SAVED");
			this.dispose();
		} catch (IOException e) {
			JOptionPane.showMessageDialog(null, "error has ocurred" + e.getMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField5 = new javax.swing.JTextField();
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTitle = new javax.swing.JTextField();
		jAuthor = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel4 = new javax.swing.JLabel();
		jISBN1 = new javax.swing.JTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Author");

		jLabel2.setText("Title");

		jLabel3.setText("ISBN ");

		jButton1.setText("Save");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jAuthor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel4.setText("ISBN");

		jMenu1.setText("Edit Book");
		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(26, 26, 26)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel4)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(layout.createSequentialGroup()
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabel3)
																				.addComponent(jLabel2))
																		.addGap(127, 127, 127)))
														.addGap(50, 50, 50)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel1)
																.addComponent(jAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(jISBN1)))
								.addGap(0, 26, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(36, 36, 36)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jISBN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
								.addComponent(jButton1)
								.addGap(19, 19, 19))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextField2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		if (jAuthor.getText().isEmpty() || jISBN1.getText().isEmpty() || jTitle.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "ERROR, enter all fields.");
		} else {
			int selectedIndex = jComboBox1.getSelectedIndex();
			books.get(selectedIndex).setISBN(jISBN1.getText());
			books.get(selectedIndex).setBookName(jTitle.getText());
			books.get(selectedIndex).setBookAuthor(jAuthor.getText());

			// TODO do we need this, we only have to worry about one combo box right?
//			Job j = jobs.get(jComboBox2.getSelectedIndex());
//			employees.get(selectedIndex).setJob(j);
			saveBooksToFile();
		}
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		int SelectedIndex = jComboBox1.getSelectedIndex();
		jISBN1.setText(books.get(SelectedIndex).getISBN());
		jTitle.setText(books.get(SelectedIndex).getBookName());
		jAuthor.setText(books.get(SelectedIndex).getBookAuthor());
//        int index = 0;
//        Student j = students.get(SelectedIndex).getJob();
//        for (int i = 0; i < jobs.size(); i++) {
//            if (jobs.get(i).equals(j)) {
//                index = i;
//                break;
//            }
//        }
//        jEmployeeComboBox.setSelectedIndex(index);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EditBook().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JTextField jAuthor;
	private javax.swing.JTextField jISBN1;
	private javax.swing.JTextField jTitle;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField5;

	// End of variables declaration//GEN-END:variables
}
